Repository URECA-T5/pawong, pull requests merged in 2024-11, with the labels that each got.

#15 feat: Add social login
  package-lock.json
  package.json
  src/api/auth/auth.js
  src/api/axios.js
  src/api/constant/api.js
  src/asset/login/Login_Img.png
  src/asset/login/Login_Img.svg
  src/asset/login/appleLogo.svg
  src/asset/login/googleLogo.svg
  src/asset/login/kakaoLogo.svg
  src/asset/login/naverLogo.svg
  src/asset/notice/dogIcon.png
  src/asset/notice/senseImg.svg
  src/components/auth/SocialLoginBtn.js
  src/components/common/GoogleLoginButton.js
  src/components/login/LoginModal.jsx
  src/config/socialLogin.js
  src/layout/DefaultLayout.jsx
  src/pages/Auth/Login/Login.jsx
  src/pages/Auth/Register/Register.jsx
  src/pages/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Menu.jsx
  src/pages/Register/Register.jsx
  src/router/router.js
  src/stores/auth/useLogin.js
  src/stores/auth/useSignup.js
  src/style/global/global.js
  src/style/login/googleBtn.js
  src/style/login/login.js
  src/style/login/socialBtn.js
  src/style/register/register.js
Labels: 희원, feat

#36 style : Delivery page publishing
  public/asset/main/dogIcon.png
  src/components/main/MainAccordion.jsx
  src/pages/Delivery/Delivery.jsx
  src/pages/Main.jsx
  src/router/router.js
  src/stores/deliveryStore.js
  src/style/delivery/delivery.js
  src/style/main/accordion.js
  src/style/main/footer.js
  src/style/main/main.js
  src/style/main/navbar.js
  src/style/record/donationReceived.js
  src/style/record/donationRecord.js
  src/style/record/donationSent.js
  src/style/record/fosterRecord.js
Labels: 은진, feat, fix, style

#40 fix: change record to history
  public/asset/history/donation.svg
  public/asset/history/donationNull.svg
  public/asset/history/foster.svg
  public/asset/history/fosterNull.svg
  public/asset/history/sample.png
  public/asset/history/sample2.png
  public/asset/history/samplebob.png
  public/asset/history/samplebob2.png
  src/components/history/DonationHistoryContent.jsx
  src/components/history/DonationHistoryNull.jsx
  src/components/history/DonationHistoryTabButton.jsx
  src/components/history/DonationReceived.jsx
  src/components/history/DonationSent.jsx
  src/components/history/FosterHistoryNull.jsx
  src/components/record/DonationRecordTabButton.jsx
  src/components/record/FosterRecordNull.jsx
  src/pages/Delivery/Delivery.jsx
  src/pages/History/DonationHistory.jsx
  src/pages/History/FosterHistory.jsx
  src/pages/Main.jsx
  src/router/router.js
  src/stores/historyStore.js
  src/style/history/donationHistory.js
  src/style/history/donationReceived.js
  src/style/history/donationSent.js
  src/style/history/fosterHistory.js
Labels: 은진, fix

#35 개별일지 페이지 퍼블리싱
  public/asset/diary/certificationBadge.svg
  public/asset/diary/dogImg.svg
  public/asset/diary/dogImg2.svg
  public/asset/diary/dogImg3.svg
  public/asset/diary/profileImg.svg
  src/pages/CareDiary/PersonalDiary.jsx
  src/router/router.js
  src/style/careDiary/careDiary.js
  src/style/careDiary/personalDiary.js
  src/style/global/global.js
Labels: 가인, style

#44 style : care diary list page publishing
  public/asset/diary/listPet.png
  src/components/diary/DiaryListContent.jsx
  src/components/diary/DiaryListTab.jsx
  src/components/diary/dummy_data.js
  src/components/history/DonationReceived.jsx
  src/components/history/DonationSent.jsx
  src/layout/DefaultLayout.jsx
  src/layout/ScrollToTop.jsx
  src/pages/CareDiary/CareDiaryList.jsx
  src/pages/Delivery/Delivery.jsx
  src/pages/History/FosterHistory.jsx
  src/pages/Main.jsx
  src/router/router.js
  src/stores/deliveryStore.js
  src/stores/diaryListStore.js
  src/style/careDiary/careDiaryList.js
  src/style/history/donationReceived.js
  src/style/history/donationSent.js
  src/style/history/fosterHistory.js
  src/style/main/main.js
Labels: 은진, fix, style

#50 style: Main 이미지 추가
  public/asset/main/carousel.jpg
  src/pages/Main.jsx
Labels: 은진, style

#43 임보일지 피드 퍼블리싱
  public/asset/diary/story/dogBowl.svg
  public/asset/diary/story/dogProfileImg.svg
  public/asset/diary/story/empty_star.svg
  public/asset/diary/story/listImg.svg
  public/asset/diary/story/star.svg
  public/asset/diary/story/storyDogImg1.svg
  public/asset/diary/story/storyDogImg2.svg
  public/asset/diary/story/storyDogImg3.svg
  src/components/diary/AuthorBtn.jsx
  src/components/diary/DefaultBtn.jsx
  src/pages/CareDiary/CareDiaryFeed.jsx
  src/router/router.js
  src/style/careDiary/careDiaryFeed.js
Labels: 가인, style

#51 [style] 관리자페이지 퍼블리싱
  public/asset/admin/cover.svg
  public/asset/admin/dogBowl.svg
  public/asset/admin/listImg.svg
  src/components/admin/AdminModal.jsx
  src/components/admin/ProductForm.jsx
  src/components/admin/ProductList.jsx
  src/components/care/diary/DiaryFeedAuthorBtn.jsx
  src/components/care/diary/DiaryFeedDefaultBtn.jsx
  src/components/care/diary/DiaryListContent.jsx
  src/components/care/diary/DiaryListTab.jsx
  src/components/care/diary/DiaryUploadImage.jsx
  src/components/care/diary/DiaryUploadInput.jsx
  src/components/care/diary/DiaryUploadInputField.jsx
  src/components/care/diary/dummy_data.js
  src/components/care/upload/UploadInputField.jsx
  src/pages/Admin/Admin.jsx
  src/pages/Care/Diary/CareDiaryDetail.jsx
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/pages/Care/Diary/CareDiaryList.jsx
  src/pages/Care/Diary/CareDiaryUpload.jsx
  src/pages/Main.jsx
  src/router/router.js
  src/stores/adminStore.js
  src/style/admin/admin.js
  src/style/care/diary/careDiaryDetail.js
  src/style/care/diary/careDiaryFeed.js
  src/style/care/diary/careDiaryList.js
  src/style/care/diary/careDiaryUpload.js
  src/style/care/upload/petUpload.js
Labels: 가인, style

#58 feat: 와글와글 임보일지 목록 연동
  src/api/diary/listAll.js
  src/components/care/diary/DiaryListContent.jsx
  src/components/care/diary/DiaryListTab.jsx
  src/pages/Care/Diary/CareDiaryList.jsx
  src/stores/diaryListStore.js
  src/style/main/accordion.js
Labels: 은진, feat, style

#39 [style] 마이페이지 구현 및 변경사항 수정
  src/asset/mypage/favPet.svg
  src/asset/mypage/historyFeed.svg
  src/asset/mypage/historyPet.svg
  src/asset/mypage/myPet.svg
  src/asset/notice/dogIcon.png
  src/asset/notice/senseImg.svg
  src/components/auth/local/LoginModal.jsx
  src/components/mypage/DefaultFav.jsx
  src/components/mypage/DefaultPet.jsx
  src/components/mypage/Login/UserFavPet.jsx
  src/components/mypage/Login/UserPet.jsx
  src/components/mypage/Login/UserProfile.jsx
  src/components/mypage/UserHistory.jsx
  src/pages/Auth/Register/Register.jsx
  src/pages/Main.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/Notice/CommonSense.jsx
  src/pages/Notice/Notice.jsx
  src/router/router.js
  src/style/main/main.js
  src/style/myPage/default.js
  src/style/myPage/mypage.js
  src/style/myPage/profile.js
  src/style/myPage/userpet.js
  src/style/register/register.js
Labels: 지욱, fix, style

#66 feat : 회원가입 페이지 유효성 검사 기능 구현
  src/pages/Auth/Register/Register.jsx
  src/style/register/register.js
Labels: 지욱, feat

#71 style : 회원정보 수정 페이지 퍼블리싱
  src/components/mypage/Login/UserProfile.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/User/EditProfile.jsx
  src/router/router.js
Labels: 지욱, style

#69 feat : MyPage 조건부 렌더링 및 사용자 프로필 구현
  src/components/mypage/Login/UserProfile.jsx
  src/pages/MyPage/MyPage.jsx
Labels: 지욱, feat

#68 [feat] 임보일지 등록 및 피드 목록 연동
  public/asset/diary/story/feedIcon.svg
  public/asset/diary/story/storyDogImg1.svg
  public/asset/diary/story/storyDogImg2.svg
  public/asset/diary/story/storyDogImg3.svg
  src/api/pet/care/diary/diaryFeed.js
  src/api/pet/care/diary/diaryUpload.js
  src/components/admin/ProductForm.jsx
  src/components/care/diary/DiaryUploadImage.jsx
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/pages/Care/Diary/CareDiaryUpload.jsx
  src/router/router.js
  src/stores/diaryFeedStore.js
  src/style/care/diary/careDiaryFeed.js
Labels: 가인, feat

#75 [feat] 임보일지 상세페이지 기능구현
  src/api/pet/care/diary/diaryDetail.js
  src/api/pet/care/diary/diaryFeed.js
  src/pages/Care/Diary/CareDiaryDetail.jsx
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/pages/Care/Diary/CareDiaryUpload.jsx
  src/pages/Menu.jsx
  src/router/router.js
  src/stores/diaryDetailStore.js
  src/style/menu/menu.js
Labels: 가인, feat

#78 Feat: Main 임보일지 api 연동
  src/components/care/diary/DiaryListContent.jsx
  src/pages/Main.jsx
Labels: 은진, feat

#72 [feat] MyPage 기능구현
  src/api/pet/care/favorites/petFavorite.js
  src/api/pet/care/list/list.js
  src/api/pet/care/userList/userList.js
  src/components/auth/logout/LogoutModal.jsx
  src/components/care/list/CareListBody.jsx
  src/components/care/list/PetProfileCard.jsx
  src/components/mypage/Login/UserPet.jsx
  src/components/mypage/Login/UserProfile.jsx
  src/config/socialLogin.js
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/pages/Care/Diary/CareDiaryUpload.jsx
  src/pages/Main.jsx
  src/stores/main/useModalStore.js
  src/stores/mypage/userPet.js
Labels: 지욱, feat

#89 [feat] 임보일지 상세페이지 기능 구현
  src/api/pet/care/diary/diaryDetail.js
  src/api/pet/care/diary/diaryUpload.js
  src/pages/Care/Diary/CareDiaryDetail.jsx
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/pages/Care/Diary/CareDiaryUpload.jsx
  src/stores/diaryDetailStore.js
  src/style/care/diary/careDiaryDetail.js
  src/style/care/diary/careDiaryFeed.js
Labels: 가인, feat

#74 test: TOSS 테스트 결제
  package-lock.json
  package.json
  src/api/donation/history/listHistory.js
  src/components/payment/ItemPrice.jsx
  src/components/payment/Toss.jsx
  src/pages/Care/Diary/CareDiaryList.jsx
  src/style/donation/itemDetail.js
Labels: 은진, feat

#83 feat : 마이페이지 즐겨찾기 기능 구현 (찐 최종)
  src/api/pet/care/favorites/getFavorite.js
  src/components/mypage/Login/UserFavPet.jsx
  src/components/mypage/UserHistory.jsx
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/pages/History/FosterHistory.jsx
  src/stores/mypage/userFavorite.js
Labels: 지욱, feat, fix, refactor

#93 [feat] 임보일지 작성 기능 최종
  src/components/care/diary/DiaryUploadInput.jsx
  src/components/care/diary/DiaryUploadInputField.jsx
  src/components/care/list/CareListBody.jsx
  src/pages/Care/Diary/CareDiaryUpload.jsx
  src/stores/diaryStore.js
  src/style/care/diary/careDiaryUpload.js
Labels: 지욱, feat, fix

#96 feat : 사용자 정보 수정 기능 구현
  src/api/auth/editProfile.js
  src/components/mypage/Login/UserProfile.jsx
  src/pages/User/EditProfile.jsx
  src/stores/auth/useProfileStore.js
  src/style/register/register.js
Labels: 지욱, feat, style

#98 feat : 마이페이지 진짜 최종 끝
  src/components/mypage/Login/UserFavPet.jsx
  src/components/mypage/Login/UserPet.jsx
  src/style/myPage/userpet.js
Labels: 지욱, feat

#101 feat : Main navbar 어드민 식별 기능 추가
  src/components/common/Nav.jsx
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/stores/auth/useUserProfile.js
  src/style/care/diary/careDiaryFeed.js
Labels: 희원, feat

#104 feat : 임보 스토리 페이지 사용자 식별 기능 추가
  package-lock.json
  package.json
  src/components/care/diary/DiaryFeedAuthorBtn.jsx
  src/components/common/Loading.jsx
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/stores/diaryFeedStore.js
Labels: 지욱, feat

#106 fix : 임보 스토리 강아지 정보 data 값 수정
  src/pages/Care/Diary/CareDiaryFeed.jsx
  src/pages/History/FosterHistory.jsx
Labels: 지욱, fix
